service: lambda-dart-sls

custom:
  defaultStage: dev

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided
  region: ap-northeast-3
  stage: ${opt:stage, self:custom.defaultStage}
  deploymentBucket: lambda-deploy-demo-221009
  ecr:
    images:
      app:
        path: ./

functions:
  main:
    image:
      name: app
    events:
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
          cors: true
