name: serverless-deploy-sample

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install sls
      run: npm i -g serverless

    - name: checkout
      uses: actions/checkout@v1

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-3
    
    - name: deploy
      if: github.ref == 'refs/heads/main'
      run: sls deploy --stage main
      if: github.ref != 'refs/heads/main'
      run: sls deploy --stage dev